name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Updated to the latest version that supports Node.js 20

      - name: Log in to Docker Hub
        uses: docker/login-action@v3  # Updated to the latest version that supports Node.js 20
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/my-python-api:latest

      - name: Push the Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-python-api:latest

      - name: Logout from Docker Hub
        run: docker logout

